secrets: {}
services:
  bartleby_transform:
    container_name: bartleby-inst_client
    environment:
      AUTODOC: 'False'
      HMD_ACCOUNT: ''
      HMD_CUSTOMER_CODE: hmdd2
      HMD_DID: aaa
      HMD_DOC_REPO_NAME: demo-config-transform-device-schema
      HMD_DOC_REPO_VERSION: '0.1'
      HMD_ENVIRONMENT: local
      HMD_REGION: reg1
      TRANSFORM_INSTANCE_CONTEXT: '{"shell": "html"}'
    image: ghcr.io/hmdlabs/hmd-tf-bartleby:0.1.19
    secrets: []
    volumes:
    - source: /home/aburg/hmdd2-demo/studio/projects/demo-config-transform-device-schema
      target: /hmd_transform/input
      type: bind
    - source: /home/aburg/hmdd2-demo/studio/projects/demo-config-transform-device-schema/target/bartleby
      target: /hmd_transform/output
      type: bind
version: '3.2'
